server: 
  contextPath: /cep
  port: 9001

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/autorizacao/user
    client:
      clientId: cep
      clientSecret: secret
      accessTokenUri: http://localhost:9000/autorizacao/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
logging:
  level:
    org.springframework:
      security: DEBUG        