# config context path to "/" by setting an empty string
server: 
  contextPath: /autorizacao
  port: 9000

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.springframework:
      security: DEBUG

datasource:
  pje:
    url: jdbc:postgresql://localhost:5432/tjma_1grau_2x
    username: postgres
    passwotd: P123456
    driver-class-name: org.postgresql.Driver
    
